@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjllMjFmN2NmNzJjNDczMGMwZWQ2MjQ4IiwiaWF0IjoxNzc2NDI2ODc2LCJleHAiOjE3NzY0Mjc3NzZ9.czNAbrGphspKAeHvDd9IjTqDdAzqaqK41v96n7kNPeg
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjllMjVmY2FmNzJjNDczMGMwZWQ2MjU3IiwiaWF0IjoxNzc2NDQzMzM4LCJleHAiOjE3NzY0NDQyMzh9.0_S6NMbWamEK7_FYkLKjlx4lysSGv8Z7ZgwQQuCGJ2k

### Las requests ya no utilizan localhost:3000
### En Railway hay que crear un "dominio público"
### La URL verdadera es la que hay en el servicio de GitHub => Settings => Networking
### En caso de haber varias, hay que ver que el puerto coincida
### Si el error es 404, es que la URL la he sacado del sitio incorrecto
### Pero si es 502, es que está usando el puerto que no es (creo)
### Para ver la base de datos desde Mongo Compass hay que buscar la URL que cuesta "egress tokens"

GET https://t11-production-1adc.up.railway.app/health

### Registrar usuario normal
POST https://t11-production-1adc.up.railway.app/api/auth/register
Content-Type: application/json

{
    "name": "Juan",
    "email": "juan@ejemplo.com",
    "password": "contraseña",
    "role": "user",
    "age": 25
}

### Registrar usuario admin
POST https://t11-production-1adc.up.railway.app/api/auth/register
Content-Type: application/json

{
    "name": "Willy",
    "email": "willy.rex@yopmail.xd",
    "password": "contraseña",
    "role": "admin",
    "age": 67
}



### Registrar usuario no válido (debería fallar)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Nadie",
    "email": "emailnovalido",
    "password": "ñ",
    "age": -1
}

### Login
POST https://t11-production-1adc.up.railway.app/api/auth/login
Content-Type: application/json

{
    "email": "juan@ejemplo.com",
    "password": "contraseña"
}

### Login admin
POST https://t11-production-1adc.up.railway.app/api/auth/login
Content-Type: application/json

{
    "email": "pulpo.pol@yopmail.xd",
    "password": "contraseña"
}


### Obtener usuario actual (necesario estar autenticado)
GET https://t11-production-1adc.up.railway.app/api/auth/me
Authorization: Bearer {{token}}

### Añadir podcast (necesario estar autenticado)
POST https://t11-production-1adc.up.railway.app/api/podcasts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "ÑÑÑ",
    "description": "No séééééé",
    "user": "69c3fbe1773596a76e5a0bf5",
    "category": "tech",
    "duration": 120,
    "episodes": 1,
    "published": false
}

### Eliminar un podcast (necesario ser admin)
DELETE https://t11-production-1adc.up.railway.app/api/podcasts/69c3fd012d8156d204b4c840
Authorization: Bearer {{tokenAdmin}}


### Obtener un podcast por ID (debe estar publicado salvo si eres admin)
GET https://t11-production-1adc.up.railway.app/api/podcasts/69c3fead97b23f884adea45d
Authorization: Bearer {{tokenAdmin}}


### Obtener los podcasts que estén publicados solamente (con paginación)
GET https://t11-production-1adc.up.railway.app/api/podcasts?page=1&limit=2


### Obtener todos los podcasts incluyendo los no publicados (necesario ser admin - con paginación)
GET https://t11-production-1adc.up.railway.app/api/podcasts/admin/all?page=1&limit=5
Authorization: Bearer {{tokenAdmin}}


### Actualizar un podcast (necesario ser el autor o ser admin)
PUT https://t11-production-1adc.up.railway.app/api/podcasts/69c2d6bdb99064813d1e46f4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Nuevo título actualizado",
  "description": "Nueva descripción más larga para el podcast...",
  "duration": 500
}


### Publicar un podcast (necesario ser admin)
PATCH https://t11-production-1adc.up.railway.app/api/podcasts/69c3fead97b23f884adea45d/publish
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}


### Despublicar un podcast (necesario ser admin)
PATCH https://t11-production-1adc.up.railway.app/api/podcasts/69c3fead97b23f884adea45d/unpublish
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}
